export const QUERIES = {
  INVENTORY: {
    ADD_ITEM:
      'INSERT INTO INVENTORY (ITEM_ID, ITEM_NAME, QUANTITY, PRICE, USER_ID) VALUES ? ON DUPLICATE KEY UPDATE QUANTITY=QUANTITY+VALUES(QUANTITY);',
    GET_ITEM:
      'SELECT * FROM INVENTORY WHERE ITEM_ID LIKE ? OR ITEM_NAME LIKE ? ORDER BY LAST_UPDATED_DATE DESC',
    DELETE_ITEM: 'DELETE FROM INVENTORY WHERE ITEM_ID IN (?);',
    UPDATE_ITEM:
      'UPDATE INVENTORY SET ITEM_ID=?,ITEM_NAME=?,QUANTITY=?,PRICE=?,USER_ID=? WHERE ITEM_ID=?;',
    UPDATE_INVENTORY:
      'INSERT INTO INVENTORY (ITEM_ID, ITEM_NAME, QUANTITY, PRICE, USER_ID) VALUES ? ON DUPLICATE KEY UPDATE QUANTITY=QUANTITY-VALUES(QUANTITY);',
  },
  BILLING: {
    ADD_BILL:
      'INSERT INTO BILLING (CUSTOMER_ID, ITEMS, CGST, SGST, ITEMS_COST, TOTAL_COST, PAYMENT_MODE, USER_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
    GET_BILL:
      'SELECT * FROM BILLING JOIN CUSTOMER ON CUSTOMER.CUSTOMER_ID=BILLING.CUSTOMER_ID ORDER BY CREATION_DATE DESC',
    SEARCH_GET_BILL:
    'SELECT * FROM BILLING JOIN CUSTOMER ON CUSTOMER.CUSTOMER_ID=BILLING.CUSTOMER_ID',
  },
  CUSTOMER: {
    ADD_CUSTOMER:
      'INSERT INTO CUSTOMER (PHONE_NUMBER, CUSTOMER_NAME, NO_OF_VISITS) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE NO_OF_VISITS=NO_OF_VISITS+1',
    EXISTING_CUSTOMER: 'SELECT CUSTOMER_ID FROM CUSTOMER WHERE PHONE_NUMBER=?',
    UPDATE_CUSTOMER_VISIT:
      'UPDATE CUSTOMER SET NO_OF_VISITS=NO_OF_VISITS+1 WHERE CUSTOMER_ID=?;',
    SEARCH_CUSTOMER: 'SELECT * FROM CUSTOMER',
  },
};
